import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

// ---- Primitive colors (hex) ----
const primitiveColors = {
  white: '#FFFFFF',
  stone50: '#FAF8F5', stone100: '#F4F1EC', stone200: '#E8E1D8',
  stone300: '#D5CBC0', stone400: '#B5AAA0', stone500: '#8B8177',
  stone600: '#6C635B', stone700: '#4B453F', stone800: '#332F2B',
  stone900: '#24201D',
  oak50: '#FFF7E8', oak100: '#FBEBCB', oak200: '#F1D59C',
  oak300: '#E0BB67', oak400: '#C99F42', oak500: '#B88E2F',
  oak600: '#946E22', oak700: '#74531A',
  success50: '#EAF7EF', success500: '#2F7D57', success700: '#1E5B3D',
  warning50: '#FFF6DD', warning500: '#B7791F',
  danger50: '#FFF0F0', danger500: '#C23B3B',
  info50: '#EEF5FF', info500: '#3973C6',
};

// ---- Semantic color mappings ----
const semanticColors = {
  background: 'stone50', surface: 'white',
  surfaceMuted: 'stone100', surfaceSubtle: 'stone50',
  textPrimary: 'stone900', textSecondary: 'stone600',
  textMuted: 'stone500', textInverse: 'white',
  borderDefault: 'stone200', borderStrong: 'stone300', borderFocus: 'oak500',
  brand: 'oak500', brandHover: 'oak600', brandActive: 'oak700', brandSoft: 'oak100',
  success: 'success500', successBg: 'success50',
  warning: 'warning500', warningBg: 'warning50',
  danger: 'danger500', dangerBg: 'danger50',
  info: 'info500', infoBg: 'info50',
};

// ---- Convert hex to HSL string (for shadcn compatibility) ----
function hexToHsl(hex) {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  let h = 0, s = 0;
  const l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = ((g - b) / d + (g < b ? 6 : 0)) / 6; break;
      case g: h = ((b - r) / d + 2) / 6; break;
      case b: h = ((r - g) / d + 4) / 6; break;
    }
  }
  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

// ---- Spacing ----
const spacing = {
  0: '0', 1: '4px', 2: '8px', 3: '12px', 4: '16px',
  5: '20px', 6: '24px', 8: '32px', 10: '40px',
  12: '48px', 16: '64px', 20: '80px', 24: '96px',
};

// ---- Radius ----
const radius = {
  xs: '2px', sm: '4px', md: '8px', lg: '12px', xl: '16px', full: '9999px',
};

// ---- Shadows ----
const shadows = {
  none: 'none',
  xs: '0 1px 2px rgba(36, 32, 29, 0.04)',
  sm: '0 4px 12px rgba(36, 32, 29, 0.06)',
  md: '0 12px 30px rgba(36, 32, 29, 0.10)',
};

// ---- Build CSS ----
let css = '/* Auto-generated by packages/design-tokens/scripts/build-css.mjs — DO NOT EDIT */\n\n';
css += ':root {\n';

// Primitive color vars
css += '  /* Primitive Colors */\n';
for (const [key, hex] of Object.entries(primitiveColors)) {
  const varName = key.replace(/([A-Z])/g, '-$1').toLowerCase();
  css += `  --color-${varName}: ${hex};\n`;
  css += `  --color-${varName}-hsl: ${hexToHsl(hex)};\n`;
}

// Semantic color vars (point to primitive hex values)
css += '\n  /* Semantic Colors */\n';
for (const [key, primitiveKey] of Object.entries(semanticColors)) {
  const varName = key.replace(/([A-Z])/g, '-$1').toLowerCase();
  const hex = primitiveColors[primitiveKey];
  css += `  --${varName}: ${hex};\n`;
  css += `  --${varName}-hsl: ${hexToHsl(hex)};\n`;
}

// Spacing vars
css += '\n  /* Spacing */\n';
for (const [key, val] of Object.entries(spacing)) {
  css += `  --spacing-${key}: ${val};\n`;
}

// Radius vars
css += '\n  /* Radius */\n';
for (const [key, val] of Object.entries(radius)) {
  css += `  --radius-${key}: ${val};\n`;
}

// Shadow vars
css += '\n  /* Shadows */\n';
for (const [key, val] of Object.entries(shadows)) {
  css += `  --shadow-${key}: ${val};\n`;
}

// Layout
css += '\n  /* Layout */\n';
css += '  --container-max-width: 1280px;\n';
css += '  --header-height-desktop: 80px;\n';
css += '  --header-height-mobile: 64px;\n';
css += '  --cart-drawer-width: 460px;\n';

css += '}\n';

mkdirSync(join(root, 'dist'), { recursive: true });
writeFileSync(join(root, 'dist', 'tokens.css'), css, 'utf-8');
console.log('✓ packages/design-tokens/dist/tokens.css generated');
